### ISSUE TITLE
Milestone 1: Project Management

### ISSUE THREAD

**Issue by mart0855** [mart0855/non-profit-website#4]
Project Management
- [x] Freshbooks account up
- [x] Project estimate (total hours)
- [x] Initial overview summary
- [x] Weekly Recap
