### ISSUE TITLE
Milestone 2: Development Team

### ISSUE THREAD

**Issue by mart0855** [mart0855/non-profit-website#6]
- [x] Information architecture breakdown and analysis
- [x] Sitemap
- [x] Gathering of site content

**Comment by mart0855** [comment]
- [x] Please remove "Chunky-Ass" from visual sitemap to be more professional
