### ISSUE TITLE
Milestone 2: Design Team

### ISSUE THREAD

**Issue by mart0855** [mart0855/non-profit-website#7]
- [x] Upload scanned jpgs of sketches to github milestone 1 folder
- [x]  Wireframes based on the IA (information architecture) & sitemap
- [x] Kayla: Landing Page
- [x] Kayla: Reports tabular 
- [x] Chelsey: Missions Values & Goals
- [x] Chelsey: Donations

**Comment by kaylaaraujo** [comment]
I uploaded my scans. Just waiting for Chelsey to put the ones she did on here :)
